//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.DoubleClickOnShape
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DoubleClickOnShape";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DoubleClickOnShape";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DoubleClickOnShapeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DoubleClickOnShapeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DoubleClickOnShapeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DoubleClickOnShapeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDoubleClickOnShapeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DoubleClickOnShapeCommandSetId), 0x0001);
	
		// Package identifier
		public const string DoubleClickOnShapePackageId = "a246c725-63a5-4e66-b81b-a0c6ce0cecab";
		
		// Editor factory identifier
		public const string DoubleClickOnShapeEditorFactoryId = "31e8c940-b767-4289-8f5d-6123892abeac";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DoubleClickOnShapeModelExplorerToolWindowId = "c5b46082-ab55-45b4-bdf1-1bee0ef6c61b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.DoubleClickOnShape
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DoubleClickOnShapeCommandSetId = "d8479aa6-0571-4a58-aa56-c4badb3be003";
	}
}